services:
  # Backend API (using Supabase database)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tennis-connect-backend
    environment:
      - APP_ENV=production
      - DB_HOST=${DB_HOST:-db.idxkilpwsbxuwgwowwfg.supabase.co}
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_SSLMODE=require
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=30
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - tennis-connect-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production  # Use production stage
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8080/api}
        - REACT_APP_ENV=production
    container_name: tennis-connect-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tennis-connect-network
    restart: unless-stopped

networks:
  tennis-connect-network:
    driver: bridge 