services:
  # Backend API (using Supabase database)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tennis-connect-backend
    environment:
      - APP_ENV=development
      - DB_HOST=${DB_HOST:-db.idxkilpwsbxuwgwowwfg.supabase.co}
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-sNDA?VjXK7$3Vhy}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_SSLMODE=require
      - JWT_SECRET=tennis-connect-dev-secret-change-in-production
      - JWT_EXPIRATION=60
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - tennis-connect-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/tmp  # Exclude tmp directory from volume mount
    develop:
      watch:
        - action: rebuild
          path: ./backend
          ignore:
            - tmp/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development  # Use development stage
      args:
        - REACT_APP_API_URL=http://localhost:8080/api
        - REACT_APP_ENV=development
        - BROWSER=none
        - CHOKIDAR_USEPOLLING=true
    container_name: tennis-connect-frontend
    environment:
      - BROWSER=none
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tennis-connect-network
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync  
          path: ./frontend/public
          target: /app/public

networks:
  tennis-connect-network:
    driver: bridge 