# Development overrides for docker-compose

services:
  backend:
    # Use development Dockerfile with Go runtime
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/tmp  # Anonymous volume to prevent air temp files from syncing to host
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_SSLMODE=disable
      - JWT_SECRET=dev-secret-key-not-for-production
    command: sh -c "go mod download && air -c .air.toml"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    # Use development Dockerfile with Node runtime
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For Windows WSL2 compatibility
    ports:
      - "3000:3000"  # Use development server port
    stdin_open: true
    tty: true

  db:
    # Development database with exposed port
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tennis_connect_dev 