# Production overrides for docker-compose
version: '3.8'

services:
  backend:
    # Production backend configuration
    restart: always
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_SSLMODE=require
      - JWT_SECRET=${JWT_SECRET}  # Must be set in environment
      - JWT_EXPIRATION=30  # Shorter expiration for production
    # Remove volume mounts for production
    volumes: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    # Production frontend - static files served by nginx
    restart: always
    # Remove development volumes
    volumes: []
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_ENV=production

  db:
    # Production database configuration
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Don't expose database port in production
    ports: []
    command: postgres -c log_statement=all -c log_duration=on
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Add backup volume in production
      - ./backups:/backups 